name: Fly Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: Checking out
        uses: actions/checkout@master

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: cd WebApi
      - run: flyctl deploy --remote-only -a web-api
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
